version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: chatapp-back-postgres-1
    restart: always
    volumes:
      - ~/volumes/tarun/postgresql/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatapp_backend
      POSTGRES_USER: tarun
      POSTGRES_PASSWORD: 235315
    ports:
      - 127.0.0.1:5432:5432